---

- name:
  become: true
  hosts: [web_servers]

  tasks:

    #  - include_tasks: roles/updates/main.yml
    #  - include_tasks: roles/wait/main.yml
    #  - include_tasks: roles/copy/main.yml
  - include_tasks: roles/nodejs/start_node.yml
