---
        #- name: check Install Node and NPM
        #  become: true
        #  become_user: it
        #  shell:
        #   "npm -v && nodejs -v"
        #  register: versioninfo
        #- name: Copying example.env file
        #  tags: project,env
        #  shell:
        #    "mv example.env .env"
        #  args:
        #    chdir: "/var/www/ingotbrokers-portal"
        #  register: RenamingEnv

  #- name: Replacing Variable in Env file
  #  tags: envnode,node
  #  lineinfile:
  #    path: /var/www/ingotbrokers-admin/.env
  #    regexp: "3002"
  #    line: "3010"
  #    state: present
  #    backup: yes
  #  register: oldport
  #
- name: Set Env File Variables
  lineinfile: dest=/var/www/ingotbrokers-portal/.env regexp='^NUXT_PORT=' line=NUXT_PORT=3003

- name: Validate that's the port is 3003
  tags: envnode,node
  lineinfile:
    path: /var/www/ingotbrokers-portal/.env
    regexp: "3003"
    state: absent
    backup: yes
  register: newport

- name: Replace Project Name in Env File
  lineinfile: dest=/var/www/ingotbrokers-portal/.env regexp='^NUXT_ENV_PROJECT_NAME=' line=NUXT_ENV_PROJECT_NAME=ingot-client

- name: Replace Portal Type in Env File
  lineinfile: dest=/var/www/ingotbrokers-portal/.env regexp='^NUXT_ENV_PORTAL_TYPE=' line=NUXT_ENV_PORTAL_TYPE==client

- name: Validate that's the portal type is employee
  lineinfile:
    path: /var/www/ingotbrokers-portal/.env
    regexp: NUXT_ENV_PORTAL_TYPE=client
    state: absent
    backup: yes
  register: typeemployee

- name: Validate that's the Project Name is ingot-client
  lineinfile:
    path: /var/www/ingotbrokers-portal/.env
    regexp: NUXT_ENV_PROJECT_NAME=ingot-client
    state: absent
    backup: yes
  register: typeclient

- name: Comment a line in env file
  lineinfile:
    path: /var/www/ingotbrokers-portal/.env
    regexp: '(^DEBUG=.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: commentinenv

- name: Comment HOST  in Env file
  lineinfile:
    path: /var/www/ingotbrokers-portal/.env
    regexp: '(^NUXT_HOST==.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: commenthost

- name: Add a line in Env File
  lineinfile: dest=/var/www/ingotbrokers-portal/.env regexp='^NUXT_ENV_DEFAULT_ENTITY=' line=NUXT_ENV_DEFAULT_ENTITY=dev.ingotbrokers.com

- name: Add a line in Env File
  lineinfile: dest=/var/www/ingotbrokers-portal/.env regexp='^NUXT_ENV_PROXY_TARGET_BASE_URL=' line=NUXT_ENV_PROXY_TARGET_BASE_URL=https://dev.ingotbrokers.com

- name: Add a line in Env File
  lineinfile: dest=/var/www/ingotbrokers-portal/.env regexp='^NUXT_ENV_TRANSLATIONS_API_URL=' line=NUXT_ENV_TRANSLATIONS_API_URL=https://dev.ingotbrokers.com

- name: Install npm in the project directory
  tags: node
  become: true
  async: 3600
  poll: 10
  shell:
    "npm install && pm2 update"
  args:
    chdir: "/var/www/ingotbrokers-portal"
  register: npminstall

  #- name: Validate npm installation
  #  debug: msg="Installation of node is Successfull"

- name: Start Node
  tags: node
  become: true
  async: 3600
  poll: 10
  shell:
    "sh deploy.sh && pm2 start"
  args:
    chdir: "/var/www/ingotbrokers-portal"
  register: appstart

- name: Validating the port is open
  tags: nodevalidate,node
  wait_for:
    host: "localhost"
    port: "3003"
    delay: "10"
    timeout: "30"
    state: started
    msg: "NodeJS server is not running"
