---
        #- name: check Install Node and NPM
        #  become: true
        #  become_user: it
        #  shell:
        #   "npm -v && nodejs -v"
        #  register: versioninfo
- name: Copying example.env file
  tags: project,env
  shell:
    "mv example.env .env"
  args:
    chdir: "{{ destdir }}"
<<<<<<< HEAD
  register: Renamingenv

  #- name: Replacing Variable in Env file
  #  tags: envnode,node
  #  lineinfile:
  #    path: /var/www/ingotbrokers-admin/.env
  #    regexp: "3002"
  #    line: "3010"
  #    state: present
  #    backup: yes
  #  register: oldport
- name
=======
  register: RenamingEnv
>>>>>>> 80e7faf (Resloving merge conflict with local)

- name: Validate that's the port is 3010
  tags: envnode,node
  lineinfile:
    path: /var/www/ingotbrokers-admin/.env
    regexp: "3010"
    state: absent
    backup: yes
  register: newport

- name: Validate that's the portal type is employee
  tags: envnode,node
  lineinfile:
    path: /var/www/ingotbrokers-admin/.env
    regexp: NUXT_ENV_PORTAL_TYPE=employe
    state: absent
    backup: yes
  register: typeemployee

- name: Comment a line in env file
  tags: envnode
  lineinfile:
    path: /var/www/ingotbrokers-admin/.env
    regexp: '(^DEBUG=.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: commentinenv

- name: Comment HOST  in Env file
  tags: envnode,node
  lineinfile:
    path: /var/www/ingotbrokers-admin/.env
    regexp: '(^NUXT_HOST==.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: commenthost

- name: Install npm in the project directory
  tags: node
  become: true
  async: 60
  poll: 10
  shell:
    "npm install"
  args:
    chdir: "{{ destdir }}"
  register: npminstall

  #- name: Validate npm installation
  #  debug: msg="Installation of node is Successfull"

- name: Start Node
  tags: node
  become: true
  async: 240
  poll: 10
  shell:
    "sh deploy.sh"
  args:
    chdir: "{{ destdir }}"
  register: appstart

- name: Validating the port is open
  tags: nodevalidate,node
  wait_for:
    host: "localhost"
    port: 3010
    delay: 10
    timeout: 30
    state: started
    msg: "NodeJS server is not running"
