---

- name: check Install Node and NPM
  shell:
    "npm -v && nodejs -v"
  register: versioninfo

- name: Copying example.env file
  tags: project,env
  shell:
    "mv example.env .env"
  args:
<<<<<<< HEAD
    chdir: "{{ destdir }}"
<<<<<<< HEAD
  register: RenamingEnv
=======
  chdir: "{{ destdir[2] }}"
  register: Env_File
=======
<<<<<<< HEAD
  register: Renamingenv
>>>>>>> dc4a20f (in rebase mode)

<<<<<<< HEAD
- name: Replacing NUXT_PORT Value
  tags: envnode,node
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_PORT='
    line: NUXT_PORT=
    state: present
  register: NUXT_PORT
>>>>>>> local
=======
  #- name: Replacing Variable in Env file
  #  tags: envnode,node
  #  lineinfile:
  #    path: /var/www/ingotbrokers-admin/.env
  #    regexp: "3002"
  #    line: "3010"
  #    state: present
  #    backup: yes
  #  register: oldport
- name
<<<<<<< HEAD
>>>>>>> f0f0988 (hosts file)
=======
=======
  register: RenamingEnv
>>>>>>> 80e7faf (Resloving merge conflict with local)
>>>>>>> dc4a20f (in rebase mode)

- name: Validate NUXT_PORT is
  lineinfile:
<<<<<<< HEAD
    path: /var/www/ingotbrokers-admin/.env
    regexp: "3010"
    state: absent
    backup: yes
  register: newport

- name: Validate that's the portal type is employee
  tags: envnode,node
  lineinfile:
    path: /var/www/ingotbrokers-admin/.env
    regexp: NUXT_ENV_PORTAL_TYPE=employe
    state: absent
    backup: yes
  register: typeemployee
=======
    path: "{{ destdir[2] }}"
    regexp: NUXT_PORT=
    state: present
  register: NUXT_PORT
>>>>>>> local

- name: Comment a line in env file
  lineinfile:
    path: /var/www/ingotbrokers-portal/.env
    regexp: '(^DEBUG=.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: DEBUGHASHED

- name: Comment HOST  in Env file
  lineinfile:
    path: /var/www/ingotbrokers-portal/.env
    regexp: '(^NUXT_HOST=.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: NUXT_HOST

- name:
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: 
    line:
    state: present
  register:

- name:
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp:
    line:
    state: present
  register:

- name:
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp:
    line:
    state: present
  register:

- name: Install npm in the project directory
  tags: node
  become: true
  async: 3600
  poll: 10
  shell:
    "npm install && pm2 update"
  args:
    chdir: "/var/www/ingotbrokers-portal"
  register: npminstall

- name: Validate npm installation
  debug: msg="Installation of node is Successfull"

- name: Start Node
  tags: node
  become: true
  async: 3600
  poll: 10
  shell:
    "sh deploy.sh && pm2 start"
  args:
    chdir: "/var/www/ingotbrokers-portal"
  register: appstart

- name: Validating the port is open
  tags: nodevalidate,node
  wait_for:
    host: "localhost"
    port: "3003"
    delay: "10"
    timeout: "30"
    state: started
    msg: "NodeJS server is not running"
