---

- name: check Install Node and NPM
  shell:
    "npm -v && nodejs -v"
  register: versioninfo

- name: Replace NUXT_ENV_API_BASE_URL Value in env file
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_API_BASE_URL='
    line: NUXT_ENV_API_BASE_URL=/
    state: present
  register: API_BASE_URL

- name: Validate's API_BASE_URL
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: NUXT_ENV_API_BASE_URL=/
    state: present
  register: API_BASE_URL

- name: Replace PROJECT_NAME in Env File
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_PROJECT_NAME='
    line: NUXT_ENV_PROJECT_NAME=ingot-client
    state: present
  register: PROJECT_NAME

- name: Validate's PROJECT_NAME
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: NUXT_ENV_PROJECT_NAME=ingot-client
    state: present
  register: PROJECT_NAME

- name: Replace PORTAL_TYPE in Env File
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_PORTAL_TYPE='
    line: NUXT_ENV_PORTAL_TYPE=client
    state: present
  register: PORTAL_TYPE

- name: Validate's PORTAL_TYPE
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: NUXT_ENV_PORTAL_TYPE=client
    state: present
  register: PORTAL_TYPE

- name: Comment a line in env file
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '(^DEBUG=.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: commentinenv

- name: Comment NUXT_HOST  in Env File
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '(^NUXT_HOST=localhost)'
    line: '# \1'
    backrefs: yes
    state: present
  register: NUXT_HOST

- name: Replace NUXT_ENV_PROXY_TARGET_BASE_URL in Env File
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_PROXY_TARGET_BASE_URL='
    line: NUXT_ENV_PROXY_TARGET_BASE_URL=https://dev.ingotbrokers.com
    state: present
  register: PROXY_TARGET_BASE_URL

- name: Validate's PROXY_TARGET_BASE_URL
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: NUXT_ENV_PROXY_TARGET_BASE_URL=https://dev.ingotbrokers.com
    state: present
    register: PROXY_TARGET_BASE_URL

- name: Replace NUXT_ENV_TRANSLATIONS_API_URL in Env File
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_TRANSLATIONS_API_URL='
    line: NUXT_ENV_TRANSLATIONS_API_URL=https://dev.ingotbrokers.com
    state: present
  register: TRANSLATIONS_API_URL

- name: Validate's TRANSLATIONS_API_URL
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: NUXT_ENV_TRANSLATIONS_API_URL=https://dev.ingotbrokers.com
    state: present
  register: TRANSLATIONS_API_URL

- name: Replace NUXT_ENV_DEFAULT_ENTITY Value in Env File
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_DEFAULT_ENTITY='
    line: NUXT_ENV_DEFAULT_ENTITY=dev.ingotbrokers.com
    state: present
  register: DEFAULT_ENTITY

- name: Validate's DEFAULT_ENTITY
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: NUXT_ENV_DEFAULT_ENTITY=dev.ingotbrokers.com
    state: present
  register: DEFAULT_ENTITY

- name: Install NPM
  tags: node,npm
  async: 3600
  poll: 10
  shell:
    "npm install"
  args:
    chdir: "{{ destdir[2] }}"
  register: NPM

- name: Validate npm installation
  debug: msg="Installation of node is Successfull"

- name: Start Node
  tags: node
  become: true
  async: 3600
  poll: 10
  shell:
    "sh deploy.sh && pm2 start"
  args:
    chdir: "{{ dest_dir[2] }}"
  register: NUXT_START

- name: Validating the port is open
  tags: nodevalidate,node
  wait_for:
    host: "localhost"
    port: "3003"
    delay: "10"
    timeout: "30"
    state: started
    msg: "NodeJS server is not running"
