---

- name: Install NPM
  tags: NODE,NPM
  async: 3600
  poll: 10
  shell:
    "npm install"
  args:
    chdir: "{{ dest_dir[2] }}"
  register: NPM_START

- name: Debug npm install command
  debug:
    msg: "{{ NPM_START.stdout_lines }}"

- name: Validate npm installation
  debug: msg="Installation of node is Successfull"

#- name: Debug npm install command
#debug: msg='{{npminstlout.stdout_lines}}'
