---

- name: Install NPM
  async: 3600
  poll: 10
  shell:
    "npm install"
  args:
    chdir: "{{ dest_dir[3] }}"
  register: nodestart

- name: Start Node
  tags: node
  become: true
  async: 3600
  poll: 10
  shell:
    "sh deploy.sh && pm2 start"
  args:
    chdir: "{{ dest_dir[3] }}"
  register: appstart
