---

- name: Installation install software-properties-common
  become: true
  apt: name=software-properties-common

- name: "Repo PHP 8.0"
  become: true
  apt_repository:
    repo:
      "ppa:ondrej/php"
  register: ADD_REPO

- name: "Updating the repo"
  apt: update_cache=yes

- name: Installation PHP v8.0
  become: true
  apt: 
    name: php8.0
    state: present

- name: install packages
  become: true
  apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - nginx
      - php8.1-mbstring
      - php8.1-bcmath
      - php8.1-opcache
      - php8.1-common
      - php8.1-cli
      - php8.1-curl
      - php8.1-fpm
      - php8.1-intl
      - php8.1-json
      - php8.1-mcrypt
      - php8.1-gd
      - php8.1-mysql
      - php8.1-raph
      - php8.1-xml
      - php8.1-bz2
    state: present
    update_cache: yes

- name: ensure php8.1-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
    notify:
      - restart php8.1-fpm
      - restart nginx

- name: enable php8.1 mcrypt module
  shell: php8.1enmod mcrypt
    args:
    creates: /etc/php5/cli/conf.d/20-mcrypt.ini

- name: Clone git repository
  git: >
    dest=/var/www/ingot-api
    repo=https://github.com/laravel/laravel.git
    update=no
  user: "www-data"
  group: "www-data"
  mod: "0775"
  when: cloned|changed

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Composer Create-Project
  composer: command=create-project working_dir=/var/www/ingot-api optimize_autoloader=no
  become: yes
  become_user: www-dat
