---

- name: Add the ondrej/php PPA
  become: true
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update Cahes
  apt:
    update_cache: true

- name: Install PHP 8.1 and Nginx
  apt:
    name:
      - php8.1
      - php8.1-fpm
      - php8.1-common
      - php8.1-cli
      - php8.1-mbstring
      - php8.1-bcmath
      - php8.1-intl
      - php8.1-opcache
      - php8.1-mysql
      - php8.1-xml
      - php8.1-gd
      - php8.1-zip
      - php8.1-bz2
      - php8.1-raph
      - nginx
    state: present
    
- name: Start and Enable Nginx
  service:
    name:
      - php8.1-fpm
      - nginx
    state: started
    enabled: true
