---

- name: Clone repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
  register: repo_clone
  failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in repository' in repo_clone.msg
