---

- name: Git ingotbrokers-admin Repo
  tags: clone
  git:
    repo: "git@bitbucket.org:sigmaltd/ingotbrokers-nuxt.git"
    accept_hostkey: yes
    key_file: "files/id_rsa_uat"
    dest: "{{ dest_dir[1] }}"
