---

- name: Create Directory
  file:
    dest: "{{ dest_dir[3] }}"
    state: directory
    owner: "it"
    group: "it"
    mode: "0775"

- name: Git ingotbrokers-admin Repo
  tags: clone,admin
  git:
    repo: "git@bitbucket.org:sigmaltd/ingotbrokers.git"
    key_file: "files/id_rsa_uat"
    dest: "{{ dest_dir[3] }}"
