---
# The docker package that ships with Fedora is old and not maintained anymore.
# To get newer docker you need to go to the source.
- name: Install Repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg
  become: yes

- name: Install
  dnf:
    name:
      - docker-ce
      - docker-compose
      - python3-docker
    state: latest
  become: yes
  notify:
    - Restart Docker

- name: Create Config Directory
  become: true
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: Config Daemon
  become: true
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - Restart Docker

- name: Create Docker Group
  become: true
  group:
    name: docker
    state: present
  become: yes
  notify:
    - Restart Docker

- name: Add user to group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: docker
  notify:
    - Restart Docker

- name: LogRotate
  import_role:
    name: logrotate
    tasks_from: docker

# https://bugzilla.redhat.com/show_bug.cgi?id=1746355
# Haven't tested this with docker-ce
- name: Enable Service
  become: true
  service:
    name: docker
    state: started
    enabled: yes
# This should maybe in a dedicated logrotate role for workstations?
- name: Log Boolean
  become: true
  seboolean:
    name: logrotate_read_inside_containers
    state: yes
    persistent: yes
