---

- name: install snapd package
  become: true
  dnf:
    name:
      - snapd
    state: present

- name: Classic Symlink
  become: true
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

# https://bugs.launchpad.net/snapd/+bug/1826662
- name: Wait for snapd to Become Ready
  become: true
  shell:
    cmd: snap wait system seed.loaded
  changed_when: false

- name: Install Prune Script
  become: true
  copy:
    src: snapd-prune.sh
    dest: /usr/local/bin/snapd-prune.sh
    mode: 0755
