---

- name: Create Directory portalbeta
  file:
    dest: "{{ dest_dir[2] }}"
    state: directory
    owner: "it"
    group: "it"
    mode: "0775"

- name: Git ingotbrokers-admin Repo
  tags: clone,admin
  git:
    repo: "git@bitbucket.org:sigmaltd/ingotbrokers-admin.git"
    key_file: "files/id_rsa"
    accept_hostkey: yes
    dest: "{{ dest_dir[2] }}"

- name: Copying example.env file
  tags: ENV_FILE
  shell:
    "cp example.env .env"
  args:
    chdir: "{{ dest_dir[2] }}"
  register: ENV_NODE

- name: Replace NUXT_ENV_API_BASE_URL Value
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_API_BASE_URL='
    line: NUXT_ENV_API_BASE_URL=/
    state: present
  register: API_BASE_URL

- name: Add NUXT_PORT Value Env File
  tags: NODE_PORT
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_PORT='
    line: NUXT_PORT=3001
    state: present
  register: NODE_PORT 


- name: Replace PROJECT_NAME in Env File
  tags: PROJECT
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_PROJECT_NAME='
    line: NUXT_ENV_PROJECT_NAME=ingot-employee
    state: present
  register: PROJECT_NAME

- name: Set Portal Tybe To client
  tags: PORTAL_TYPE
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_PORTAL_TYPE='
    line: NUXT_ENV_PORTAL_TYPE=employee
    state: present
  register: PORTAL_TYPE

- name: Replace NUXT_ENV_PROXY_TARGET_BASE_URL in Env File
  tags: PROXY_URL
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_PROXY_TARGET_BASE_URL='
    line: NUXT_ENV_PROXY_TARGET_BASE_URL=https://dev.ingotbrokers.com
    state: present
  register: PROXY_TARGET_BASE_URL

- name: Replace NUXT_ENV_TRANSLATIONS_API_URL in Env File
  tags: API_URL
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_TRANSLATIONS_API_URL='
    line: NUXT_ENV_TRANSLATIONS_API_URL=https://dev.ingotbrokers.com
    state: present
  register: TRANSLATIONS_API_URL

- name: Replace NUXT_ENV_DEFAULT_ENTITY Value in Env File
  tags: ENTITY
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '^NUXT_ENV_DEFAULT_ENTITY='
    line: NUXT_ENV_DEFAULT_ENTITY=dev.ingotbrokers.com
    state: present
  register: DEFAULT_ENTITY
  
- name: Comment a line in env file
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '(^NUXT_HOST=localhost)'
    line: '# \1'
    backrefs: yes
    state: present
  register: NUXT_HOST

- name: Comment a line in env file
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '(^DEBUG=.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: DEBUG

- name: Comment CDN
  lineinfile:
    path: "{{ destdir[2] }}"
    regexp: '(^NUXT_ENV_CDN_URL=.*)'
    line: '# \1'
    backrefs: yes
    state: present
  register: DEBUG

- name: Install NPM
  tags: node
  async: 3600
  poll: 10
  shell:
    "npm init && npm install"
  args:
    chdir: "{{ dest_dir[2] }}"
  register: NPM_INSTALLED

#- name: Debug npm install command
   #debug:
   #msg: "{{ NPM_START.stdout_lines }}"

- name: Validate npm installation
  debug: msg="Installation of node Succes"

- name: PM2 Install
  become: true
  npm:
    name: pm2
    global: yes

- name: Run dev
  tags: node,dev
  async: 3600
  poll: 10
  shell:
    "sh deploy.sh"
  args:
    chdir: "{{ dest_dir[2] }}"
  register: NODE_STARTED

- name: Start PM2
  command: pm2 start
  args:
    chdir: "{{ dest_dir[2] ))"
  register: PM2_START

- name: Validating the port is open
  tags: validate,node
  wait_for:
    host: "localhost"
    port: "3001"
    delay: "10"
    timeout: "30"
    state: NODE_STARTED
