---

- name: Checking Connectivity
  hosts: localhost

  tasks:
    - name: Make a PUT Request
      uri:
        url: https://portal.ingotbrokers.com
        method: PUT
        body: '{"name": "John Smith", "age": 35}'
        body_format: json
        headers:
          Content-Type: application/json
        status_code: 200
        return_content: yes
      register: response
