---

- name: POST ON URL
  uri:
    url: https://{{ item }}.{{ domain }}/en/login/
    method: POST
    body_format: json
    body: '{"email": "qshahrour@outlook.com", "password":"Rhsl$%2022"}'
    heasers:
      content_type: "application/json"
      Connection: "keep-alive"
    status_code: 200
    return_content: yes
    validate_certs: no
    delegate_to: localhost
  when: url_check.status !=200 and url_check.status != 500
  register: url_check
  with_items:
    - portal
    - campains

- name: Print status code
  debug:
    msg: "Status code: {{ url_check.status }}"
