---

- name: restart f2b
  become: true
  service:
    name: fail2ban
    state: restarted

# The VPS doesn't do UEFI booting :(
- name: rebuild grub
  become: true
  command: grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg && grub2-mkconfig -o /boot/grub2/grub.cfg

---
# https://stackoverflow.com/questions/31618967/how-do-i-write-an-ansible-handler-with-multiple-tasks
- name: restart NetworkManager
  become: true
  service:
    name: NetworkManager
  state: restarted
  listen: restart NetworkManager

- name: wait for networking
  shell:
    cmd: 'curl -m 2 -s https://google.com'
  warn: false
  register: result
  retries: 5
  delay: 2
  until: result.rc == 0
  listen: restart NetworkManager

# Handlers For Docker
- name: restart docker
  service:
    name: docker
    state: restarted
  become: yes
  listen: restart docker

# httpd Role
- name: restart httpd
  become: true
  service: name={{ item }} state=restarted
  with_items:
    - httpd
