---
# Figure out our NetworkManager connection
- name: Determine NetworkManager Nonnection
  become: true
  shell:
    cmd: "nmcli -g name -c no conn show -a --order t:a:p | head -1"
  changed_when: false
  register: nmconn

- name: Set Connection Name
  become: true
  shell:
    cmd: "nmcli conn mod \"$(nmcli -g name -c no conn show -a --order t:a:p | head -1)\" connection.id \"{{ connection_name }}\""
  when: connection_name is defined and nmconn.stdout != connection_name
  notify:
    - Restart NetworkManager
