---
- name: install packages
  become: true
  apt:
    name:
      - NetworkManager-openvpn
      - NetworkManager-openconnect
    state: present

- name: VPN connections
  become: true
  template:
    src: "nmconn-{{ item.value.type }}.j2"
    dest: "/etc/NetworkManager/system-connections/{{ item.key }}"
    mode: 0600
    owner: root
    groupe: root
  notify:
    - restart NetworkManager
  with_dict:
    "{{ vpn_connections }}"

# Deprecated until I need it again
# #- name: GlobalProtect gateway fix script
# #  copy:
# #    src: 100-gp_gateway.sh
# #    dest: /etc/NetworkManager/dispatcher.d/100-gp_gateway.sh
# #    mode: 0755
# #  become: yes
#
- name: flush
  meta: flush_handlers
