---
# https://mapproxy.org/docs/latest/install.html
#   
- name: Install dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
#   - build-essential
#   - libapache2-mod-wsgi
#   - libfreetype6-dev
#   - libgeos-dev
#   - libgdal-dev
#   - libjpeg-dev
#   - libproj0
#   - python-dev
#   - python-imaging
#   - python-lxml
#   - python-pip
#   - python-shapely
#   - python-virtualenv
#   - python-yaml
#   - zlib1g-dev
