---

# Until CloudBerry supports filename encryption, I will be using rclone.
# # https://blog.kamens.us/2017/08/24/backing-up-from-unix-to-backblaze-b2-using-rclone/
- name: Install rclone
  become: true
  apt:
    name:
      - rclone
      - perl-File-Slurp

- name: Create rclone config
  file:
    path: /root/.config/rclone
    state: directory
  with_items:
    - /root/.config/rclone

- name: Configure rclone
  become: true
  template:
    src: rclone.conf
    dest: /root/.config/rclone/rclone.conf
    mode: "0640"

- name: Create job config directory
  become: true
  file:
    path: /etc/rclone-backups
    state: directory

- name: Create Backup Configs
  become: true
  template:
    src: job.conf
    dest: "/etc/rclone-backups/{{ item.name }}.conf"
  with_items:
    - "{{ b2_jobs }}"

- name: Install Scripts
  become: true
  copy:
    src: "{{ item.name }}"
    dest: "{{ item.path }}/{{ item.name }}"
    mode: "0755"
  with_items:
    - name: rclone-backup
      path: /usr/local/bin
    - name: z-rclone-backup-cron
      path: /etc/cron.daily
