---
        
- name: notify Slack that the servers have been updated
  tags: slack
  community.general.slack:
    token: T026******PF/B02U*****N/WOa7r**********Ao0jnWn
    msg: |
        ### StatusUpdate ###
        --------------------------------------
        ``
        `Server`: {{ansible_host}}
        `Status`: NodeJS Sample Application installed successfully
        --------------------------------------
    channel: '#ansible'
    color: good
    username: 'Ansible on {{ inventory_hostname }}'
    link_names: 0
    parse: 'none'
  delegate_to: localhost
