---

- name: API Site
  hosts: [api_servers]
  vars_files:
    - ../vars/main.yml

  pre_tasks:
    - include_tasks: ../roles/common/inventory_loop.yml
    - include_tasks: ../roles/common/chkcpu.yml
    - include_tasks: ../roles/common/chkmem.yml
    - include_tasks: ../roles/common/chkdsk.yml
    - include_tasks: ../roles/common/chkmemp.yml

  tasks:
    - include_tasks: ../roles/common/updates.yml
    - include_tasks: ../roles/
