---

- name: API URL Check
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
    - name: API Checking URL
      uri:
        url: https://api.ingotbrokers.com/v1/website/contact-requests
        method: POST
        body_format: json
        body: '{"name":"testting","email":"testting@gmail.com","message":"testting","phone_code":"123","phone_number":"123456789","contact_request_subject_id":"1"}'
        headers:
          content_type: "application/json"
          entity: "www.ingotbrokers.com"
          language: "en"
          connection: "keep-alive"
          Accept: "application/json"
        follow_redirects: all
        return_content: false
        validate_certs: false
        status_code: [422]
      register: api_status

    - name: Check API URL Status
      assert:
        that: api_status.status == 422

    - name: Ansible Email Task
      mail:
        host: smtp.office365.com
        port: 587
        username: ingotadmin@ingotbrokers.com
        password: Wax92237
        to: q.shahrour@ingotbrokers.com
        subject: API Alert Email
        body: "This is Alert Email sent by Ansible, to inform you that Error Accured at API Call"
        sender: ingotadmin@ingotbrokers.com

