---

- name: NodeJs Client Type Site
  hosts: [web_servers]
  vars_files:
    - ../vars/main.yml

    #handlers:
    #- ../handlers/main.yml

  #pre_tasks:
    #- include_tasks: ../roles/common/inventory_loop.yml
    #- include_tasks: ../roles/common/chkcpu.yml
    #- include_tasks: ../roles/common/chkmem.yml
    #- include_tasks: ../roles/common/chkdsk.yml
    #- include_tasks: ../roles/common/chkmemp.yml

  tasks:
    - include_tasks: ../roles/common/updates.yml
    - include_tasks: ../roles/nodejs/chknpm.yml
    - include_tasks: ../roles/clone/clinod.yml
    - include_tasks: ../roles/nodejs/clienv.yml
    #- include_tasks: ../roles/nodejs/nvm-builtin.yml
    - include_tasks: ../roles/nodejs/clinpm.yml
    - include_tasks: ../roles/nodejs/clideploy.yml
    - include_tasks: ../roles/nodejs/pm2.yml
    - include_tasks: ../roles/nodejs/chkport3.yml
    
  #post_tasks:
    #- include_tasks: ../roles/common/slack.yml
    #- include_tasks: ../roles/common/updates.yml
