--

- name: install the Apache2 release
  become: yes
  become_user: "{{ ansible_user }}"
  apt:
    name: apache2
    state: present

- name: Ensure Apache is at the Latest version
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - web
    - apache2
  apt:
    name: apache2
    state: latest

- name: "Create sites-available and sites-enabled Directories"
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - web
    - sites-available
  file:
    dest: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
    state: directory
  with_items:
    - "/etc/apache2/sites-enabled"
    - "/etc/apache2/sites-available"

- name: Modify the Default Apache Configuration file
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - web
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - {src: 'basic_vh.conf.j2', dest: '/etc/apache2/sites-available/{{ domain }}.conf'}
    - {src: 'apache2.conf.j2', dest: '/etc/apache2/apache2.conf'}

- name: Create the Document Root Direcotory
  become_user: "{{ ansible_user }}"
  become: yes
  tags:
    - web
  file:
    dest: "{{ docroot }}"
    mode: "0755"
    owner: apache2
    group: apache2
    state: directory

- name: Symlink the sites-available VH file to sites-enabled
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - web
  file:
    src: "/etc/apache2/sites-available/{{ domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ domain }}.conf"
    state: link
  notify: restart apache2

- name: Make Sure mime.types file is available
  tags:
    - web
  file:
    dest: /etc/apache2/mime.types
    state: file
  register: mimeout
  ignore_errors: True

- name: Copy the /etc/mime.types file to httpd conf
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - web
  shell: "cp /etc/mime.types /etc/apache2/mime.types"
  when: mimeout is failed

- name: Download the home page of www.middlewareinventory.com to tmp
  tags:
    - web
  become: yes
  become_user: "{{ ansible_user }}"
  shell:
    "wget https://www.middlewareinventory.com"
  args:
    chdir: "/tmp"
    creates: "index.html"

- name : Changing file permission of downloaded index.html and copy to DocRoot
  tags:
    - web
  become: yes
  become_user: "{{ ansible_user }}"
  copy:
    remote_src: yes
    src: "/tmp/index.html"
    dest: "{{docroot}}/index.html"
    owner: "apache2"
    group: "apache2"
    mode: "0755"

- name: Make Sure the Apache is Running
  tags:
    - web
  become: yes
  become_user: it
  service: name=apache2 state=restarted enabled=yes
