---

- name: Combine multiple conditions to override 'changed' result
  command: /bin/fake_command
  register: result
  ignore_errors: True
  changed_when:
    - '"ERROR" in result.stderr'
    - result.rc


