---

- name: Notify Slack that the Job is Failing
  tags: slack
  community.general.slack:
    token: T03QQ7RP6M9/B04KYT10F0C/2O8lHyRVJPz0U3ZU1OMixPu2
    msg: |
        ### StatusUpdate ###
        – ------------------------------------
        ``
        `Server`: {{ansible_host}}
        `Status`: Ansible File Watcher Job failed
        – ------------------------------------
    channel: '#ansible-bot'
    color: good
    username: 'Ansible on {{ inventory_hostname }}'
    link_names: 0
    parse: 'none'
  when: pull is failed
  ignore_errors: true
  
- name: notify Slack that the job is Successful
  tags: slack
  community.general.slack:
    token: T03QQ7RP6M9/B04KYT10F0C/2O8lHyRVJPz0U3ZU1OMixPu2
    msg: |
        ### StatusUpdate ###
        – ------------------------------------
        ``
        `Server`: {{ansible_host}}
        `Status`: Ansible File Watcher Job Successful.
        – ------------------------------------
    channel: '#ansible-bot'
    color: good
    username: 'Ansible on {{ inventory_hostname }}'
    link_names: 0
    parse: 'none'
    when: pull is not failed
