---

- name: Install
  become: true
  dnf:
    name: wireshark
    state: latest

- name: Add user to group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: wireshark

- name: "create config directory"
  file:
    path: '~/.wireshark'
    state: directory

- name: "preferences"
  copy:
    src: preferences
    dest: '~/.wireshark/preferences'
