---

- name: Ansible Lookup Copy the public Key Using the Key directly within Playbook
  authorized_key:
  tags: key
    user: ubuntu
    state: present
    key: ""

# IN TASK2: WE ARE READING THE PUBLIC KEY FROM THE FILE DIRECTLY USING LOOKUP
# ANSIBLE FILE LOOKUP PLUGIN HELPS TO READ THE FILE CONTENTS WITHIN THE ANSIBLE PLAYBOOK
- name: Copy the public Key using Lookup
  authorized_key:
  tags: key
    user: ubuntu
    state: present
    key: "{{ lookup(‘file’, ‘~/.ssh/id_rsa.pub’) }}"



